2021-01-25 21:22:32 | INFO     | root | Log initialized.
2021-01-25 21:22:32 | INFO     | root | This is a  msg with user: Adam.Belkada
2021-01-25 21:22:32 | ERROR    | root | division by zero
Traceback (most recent call last):
  File "c:\Users\adam.belkada\SourceControl\MyProjects\PythonLearing\src\logging\logging_messages.py", line 71, in main
    c = a/b
ZeroDivisionError: division by zero
